### PR TITLE
Use the new repository layout of lightbox2 to be compatible with version v2.7.3+.

### PR DESCRIPTION
**Pull request by bradplank**
To support lightbox2 v2.7.2:
* lightbox2 now has a `dist` path, and the `img` path is now `images`
* jQuery 2.1.4+ is a dependency

### CODE REVIEW

**Comment by ramybenaroya** [comment]
I see that there is a  2.7.4 release coming soon without paths changes nor higher jquery dependency

**Comment by bradplank** [comment]
I will update my pull request.  Sound good?

**Comment by ramybenaroya** [comment]
Cool. Keep in mind 2.7.4 has not been released yet

**Comment by bradplank** [comment]
Interesting, will look into the jQuery dependency issue.

**Comment by bradplank** [comment]
The new modifications should be compatible with lightbox2 v2.7.4 as well, glad to help out, and thank you for the heads up.

**Comment by ramybenaroya** [comment]
@bradplank, thank you for your help. your PR is available at v0.0.3. In addition to your PR, I upgraded ember-cli@0.2.7 and added a component unit test.

**Pull request merged**
